-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 13:00:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ToDo_List
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ToDo_List
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ToDo_List` DEFAULT CHARACTER SET utf8 ;
USE `ToDo_List` ;

-- -----------------------------------------------------
-- Table `ToDo_List`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDo_List`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDo_List`.`List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDo_List`.`List` (
  `idList` INT NOT NULL AUTO_INCREMENT,
  `name_list` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idList`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDo_List`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDo_List`.`Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idTask`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDo_List`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDo_List`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `name_tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDo_List`.`task_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDo_List`.`task_tag` (
  `task_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  INDEX `task_idx` (`task_id` ASC) VISIBLE,
  INDEX `tag_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `task`
    FOREIGN KEY (`task_id`)
    REFERENCES `ToDo_List`.`Task` (`idTask`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `ToDo_List`.`Tag` (`idTag`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDo_List`.`list_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDo_List`.`list_task` (
  `list_id` INT NOT NULL,
  `task_id` INT NULL,
  INDEX `list_idx` (`list_id` ASC) VISIBLE,
  INDEX `task_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `list`
    FOREIGN KEY (`list_id`)
    REFERENCES `ToDo_List`.`List` (`idList`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task`
    FOREIGN KEY (`task_id`)
    REFERENCES `ToDo_List`.`Task` (`idTask`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ToDo_List`.`user_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ToDo_List`.`user_list` (
  `uaser_id` INT NOT NULL,
  `list__id` INT NOT NULL,
  INDEX `user_idx` (`uaser_id` ASC) VISIBLE,
  INDEX `list_idx` (`list__id` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`uaser_id`)
    REFERENCES `ToDo_List`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `list`
    FOREIGN KEY (`list__id`)
    REFERENCES `ToDo_List`.`List` (`idList`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
